export const AUTH_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  SET_USER_PERMISSIONS: 'SET_USER_PERMISSIONS',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  CLEAR_AUTH_ERROR: 'CLEAR_AUTH_ERROR'
};